---
env:
  type: UnityEnv
  solved_score: 13.0
  unity:
    filename: Banana.app
    mode: vector

agent:
  type: DqnAgent
  dqn:
    model:
      type: DuelingDqnModel
      params:
        fc_units: [64, 32, 32]
    use_prioritized_experience_replay: true
    use_importance_sampling: false
    use_double_dqn: true

train:
  seed: 0
  num_episodes: 1000
  max_steps_per_episode: 0
  render_every: 100

checkpoint_dir: checkpoints