---
env:
  type: GymEnv
  solved_score: 200.0
  gym:
    id: LunarLander-v2

agent:
  type: DqnAgent
  dqn:
    model:
      type: DuelingDqnModel
      params:
        fc_units: [64, 64]
    use_prioritized_experience_replay: false
    use_importance_sampling: false
    use_double_dqn: true

train:
  seed: 1
  num_episodes: 2000
  max_steps_per_episode: 1000
  render_every: 100

checkpoint_dir: checkpoints