---
env:
  type: GymEnv
  solved_score: 200.0
  gym:
    id: LunarLander-v2

agent:
  type: DqnAgent
  dqn:
    model: DuelingDqnModel
    use_prioritized_experience_replay: true
    use_double_dqn: true

train:
  num_episodes: 2000
  max_steps_per_episode: 1000
  render_every: 100

checkpoint_dir: checkpoints